org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
systemProp.ANDROID_PREFS_ROOT=C\:\\Users\\willi\\.android_cache
systemProp.ANDROID_USER_HOME=C\:\\Users\\willi\\.android_cache
systemProp.android.home=C\:\\Users\\willi\\AppData\\Local\\Android\\Sdk
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
